export const CITIES = [
  {
    city: "가평, 양평",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["가평", "양평"],
    isSelect: false,
  },
  {
    city: "강릉, 속초",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["강릉", "속초", "양양"],
    isSelect: false,
  },
  {
    city: "경주",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["경주"],
    isSelect: false,
  },
  {
    city: "부산",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 35.2092, lng: 129.0695 },
    related: ["부산"],
    isSelect: false,
  },
  {
    city: "여수",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["여수"],
    isSelect: false,
  },
  {
    city: "인천",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["인천", "강화도"],
    isSelect: false,
  },
  {
    city: "전주",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["전주", "군산"],
    isSelect: false,
  },
  {
    city: "제주",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["제주", "서귀포"],
    isSelect: false,
  },
  {
    city: "춘천, 홍천",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["춘천", "홍천"],
    isSelect: false,
  },
  {
    city: "태안",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["태안", "당진", "서산"],
    isSelect: false,
  },
  {
    city: "통영, 거제, 남해",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["통영", "거제", "남해"],
    isSelect: false,
  },
  {
    city: "포항, 안동",
    country: "한국",
    isDomestic: true,
    region: "한국",
    location: { lat: 37.5502, lng: 126.9931 },
    related: ["포항", "안동"],
    isSelect: false,
  },
  {
    city: "도쿄",
    country: "일본",
    isDomestic: false,
    region: "일본",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["도쿄", "하코네", "요코하마, 가마쿠라"],
    isSelect: false,
  },
  {
    city: "오사카",
    country: "일본",
    isDomestic: false,
    region: "일본",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["오사카", "교토", "고베", "나라"],
    isSelect: false,
  },
  {
    city: "후쿠오카",
    country: "일본",
    isDomestic: false,
    region: "일본",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["후쿠오카", "유후인", "벳푸", "기타큐슈"],
    isSelect: false,
  },
  {
    city: "나가사키",
    country: "일본",
    isDomestic: false,
    region: "일본",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["나가사키", "사가", "사세보", "운젠"],
    isSelect: false,
  },
  {
    city: "오키나와",
    country: "일본",
    isDomestic: false,
    region: "일본",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["오키나와"],
    isSelect: false,
  },
  {
    city: "뉴욕",
    country: "미국",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["뉴욕"],
    isSelect: false,
  },
  {
    city: "로스앤젤레스",
    country: "미국",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["로스앤젤레스", "라스베가스"],
    isSelect: false,
  },
  {
    city: "하와이",
    country: "미국",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["하와이"],
    isSelect: false,
  },
  {
    city: "토론토",
    country: "케나다",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["토론토", "나이아가라", "킹스턴", "블루 마운틴"],
    isSelect: false,
  },
  {
    city: "시애틀",
    country: "케나다",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["시애틀"],
    isSelect: false,
  },
  {
    city: "샌프란시스코",
    country: "미국",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["샌프란시스코", "산호세", "나파 밸리"],
    isSelect: false,
  },
  {
    city: "벤쿠버",
    country: "캐나다",
    isDomestic: false,
    region: "미주",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["벤쿠버", "빅토리아", "휘슬러"],
    isSelect: false,
  },
  {
    city: "나트랑",
    country: "베트남",
    isDomestic: false,
    region: "동남아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["나트랑"],
    isSelect: false,
  },
  {
    city: "마닐라",
    country: "필리핀",
    isDomestic: false,
    region: "동남아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["마닐라", "바탕가스"],
    isSelect: false,
  },
  {
    city: "치앙마이",
    country: "태국",
    isDomestic: false,
    region: "동남아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["치앙마이", "치앙라이", "빠이"],
    isSelect: false,
  },
  {
    city: "라오스",
    country: "라오스",
    isDomestic: false,
    region: "동남아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["비엔티안", "방비엥", "루앙프라방"],
    isSelect: false,
  },
  {
    city: "괌",
    country: "괌",
    isDomestic: false,
    region: "남태평양",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["괌"],
    isSelect: false,
  },
  {
    city: "사이판",
    country: "사이판",
    isDomestic: false,
    region: "남태평양",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["사이판"],
    isSelect: false,
  },
  {
    city: "시드니",
    country: "오스트레일리아",
    isDomestic: false,
    region: "남태평양",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["시드니", "블루마운틴", "울릉공", "뉴캐슬"],
    isSelect: false,
  },
  {
    city: "런던",
    country: "영국",
    isDomestic: false,
    region: "유럽",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["런던", "옥스퍼드", "브라이튼", "이튼"],
    isSelect: false,
  },
  {
    city: "파리",
    country: "프랑스",
    isDomestic: false,
    region: "유럽",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["파리", "베르사유", "몽생미셀", "스트라스부르"],
    isSelect: false,
  },
  {
    city: "두바이",
    country: "아랍에미리트",
    isDomestic: false,
    region: "서아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["두바이", "아부다비", "알 아인"],
    isSelect: false,
  },
  {
    city: "이스탄불",
    country: "튀르키예",
    isDomestic: false,
    region: "서아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["이스탄불", "부르사", "아즈닉"],
    isSelect: false,
  },
  {
    city: "카파도키아",
    country: "튀르키예",
    isDomestic: false,
    region: "서아시아",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["카파도키아", "코니아"],
    isSelect: false,
  },
  {
    city: "홍콩",
    country: "홍콩",
    isDomestic: false,
    region: "중화/중국",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["홍콩", "마카오"],
    isSelect: false,
  },
  {
    city: "베이징",
    country: "중국",
    isDomestic: false,
    region: "중화/중국",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["베이징"],
    isSelect: false,
  },
  {
    city: "타이베이",
    country: "대만",
    isDomestic: false,
    region: "중화/중국",
    location: { lat: 33.4825, lng: 126.5311 },
    related: ["타이베이", "이란"],
    isSelect: false,
  },
];
